const $ = (id) => document.getElementById(id);
const state = { hp:100, enemyHp:100, star:0, combo:0, time:60, round:1, active:false, keys:new Set(), enemyBusy:false };
const player = $('player'), enemy = $('enemy');
function update(){ $('playerHp').style.width = `${Math.max(0,state.hp)}%`; $('enemyHp').style.width = `${Math.max(0,state.enemyHp)}%`; $('starMeter').style.width = `${state.star}%`; $('combo').textContent = `${state.combo} HIT COMBO`; $('timer').textContent = String(state.time).padStart(2,'0'); }
function message(title, sub, hide=false){ $('roundMessage').innerHTML=`<b>${title}</b><span>${sub}</span>`; $('roundMessage').classList.toggle('hidden',hide); }
function flash(text){ const el=$('impact'); el.textContent=text; el.classList.remove('show'); void el.offsetWidth; el.classList.add('show'); }
function start(){ state.active=true; state.hp=100; state.enemyHp=100; state.star=0; state.combo=0; state.time=60; state.round=1; update(); message('FIGHT!','MAKE YOUR MOVE'); setTimeout(()=>message('','',true),850); $('status').textContent='FIGHT!'; }
function dodge(dir){ if(!state.active)return; player.style.transform=`translateX(${dir*42}px) rotate(${dir*5}deg)`; setTimeout(()=>player.style.transform='',180); $('status').textContent=dir<0?'DODGE LEFT':'DODGE RIGHT'; }
function block(on){ if(!state.active)return; player.classList.toggle('blocking',on); $('status').textContent=on?'BLOCKING':'FIGHT!'; }
function attack(type){ if(!state.active || state.enemyBusy)return; state.enemyBusy=true; let damage=type==='star'?30:type==='upper'?16:10; if(type==='star' && state.star<100){state.enemyBusy=false; flash('CHARGE!'); return} state.enemyHp-=damage; state.combo++; if(type!=='star')state.star=Math.min(100,state.star+12); enemy.classList.add('hurt'); flash(type==='star'?'STAR!':type==='upper'?'UP!':'POW!'); $('status').textContent=type==='star'?'STAR PUNCH!':type==='upper'?'UPPERCUT':'BODY BLOW'; update(); setTimeout(()=>{enemy.classList.remove('hurt'); state.enemyBusy=false; enemyTurn();},260); if(state.enemyHp<=0) finish(true); }
function enemyTurn(){ if(!state.active)return; setTimeout(()=>{if(!state.active)return; if(player.classList.contains('blocking')){flash('GUARD'); state.hp=Math.max(0,state.hp-2)}else{const hit=Math.random()<.25?0:Math.floor(Math.random()*8)+5; if(hit){state.hp-=hit; player.classList.add('hurt'); flash('OUCH!'); setTimeout(()=>player.classList.remove('hurt'),250)}} update(); if(state.hp<=0)finish(false)},420); }
function finish(win){ state.active=false; $('status').textContent=win?'KO!':'DOWN!'; message(win?'KNOCKOUT!':'TRY AGAIN',win?'DOWNTOWN CIRCUIT CLEARED':'PRESS RESTART TO FIGHT'); }
document.addEventListener('keydown',(e)=>{const key=e.key.toLowerCase(); if(['a','d','s','w','p',' '].includes(key))e.preventDefault(); if(state.keys.has(key))return; state.keys.add(key); if(key==='a'&&!state.keys.has('w'))dodge(-1); if(key==='d'&&!state.keys.has('w'))dodge(1); if(key==='s')block(true); if(key===' ' )attack('body'); if(key==='p')attack('star'); if((key==='a'||key==='d')&&state.keys.has('w'))attack('upper');});
document.addEventListener('keyup',(e)=>{const key=e.key.toLowerCase();state.keys.delete(key);if(key==='s')block(false);});
$('restart').addEventListener('click',start); setInterval(()=>{if(state.active&&state.time>0){state.time--;update();if(state.time===0)finish(state.enemyHp<state.hp)}},1000); update();
