const fighters=[{name:'VOLT BRICK',hp:100,jab:8,hook:12,upper:16,pattern:['jab','jab','hook','pause']},{name:'IRON GLO',hp:115,jab:10,hook:14,upper:18,pattern:['pause','block','hook','upper']},{name:'NOVA BLADE',hp:125,jab:12,hook:16,upper:20,pattern:['dodge','jab','pause','upper','hook']},{name:'CROWN ZERO',hp:160,jab:14,hook:20,upper:25,pattern:['feint','jab','hook','pause','upper','block'],boss:true}];
const $=id=>document.getElementById(id),e={titleScreen:$('titleScreen'),round:$('roundLabel'),timer:$('timer'),php:$('playerHp'),ehp:$('enemyHp'),ptext:$('playerHealthText'),etext:$('enemyHealthText'),status:$('statusText'),ename:$('enemyName'),impact:$('impactText'),combo:$('comboText'),star:$('starMeter'),player:$('player'),enemy:$('enemy'),banner:$('messageBanner'),title:$('messageTitle'),sub:$('messageSub'),start:$('startButton'),restart:$('restartButton'),music:$('musicButton'),telegraph:$('telegraph'),teleMove:$('telegraphMove'),teleTarget:$('telegraphTarget'),teleProgress:$('telegraphProgress')};
const s={active:false,over:false,round:0,index:0,php:100,pmax:100,ehp:100,emax:100,star:0,combo:0,time:60,busy:false,enemyBusy:false,block:false,pressed:new Set(),enemyTimer:null,clock:null,telegraphTimer:null,telegraphId:0,musicOn:true,audio:null,pattern:0};
function hud(){e.php.style.width=`${Math.max(0,s.php/s.pmax*100)}%`;e.ehp.style.width=`${Math.max(0,s.ehp/s.emax*100)}%`;e.star.style.width=`${s.star}%`;e.ptext.textContent=`${Math.ceil(s.php)} / ${s.pmax}`;e.etext.textContent=`${Math.ceil(s.ehp)} / ${s.emax}`;e.combo.textContent=`${s.combo} HIT COMBO`;e.timer.textContent=String(s.time).padStart(2,'0');e.round.textContent=s.round}
function banner(a,b,show=true,kind=''){e.title.textContent=a;e.sub.textContent=b;e.banner.className=`message-banner ${show?'':'hidden'} ${kind}`}
function hitText(t){e.impact.textContent=t;e.impact.classList.remove('show');void e.impact.offsetWidth;e.impact.classList.add('show')}
function tone(type='hit'){const C=AudioContext||webkitAudioContext;if(!C)return;if(!s.audio)s.audio=new C;const c=s.audio,o=c.createOscillator(),g=c.createGain(),power=type==='power';o.type=power?'sawtooth':'square';o.frequency.setValueAtTime(type==='ko'?80:power?130:250,c.currentTime);o.frequency.exponentialRampToValueAtTime(55,c.currentTime+.22);g.gain.setValueAtTime(.035,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.23);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.24)}
function music(){if(!s.active||!s.musicOn||!s.audio)return;const c=s.audio,o=c.createOscillator(),g=c.createGain();o.type='triangle';o.frequency.value=s.index===3?110:165;g.gain.value=.01;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.28);setTimeout(music,700)}
function anim(who,cls,ms){who.classList.remove('punch-body','punch-upper','punch-star','dodge-left','dodge-right','hurt','ko','recover');who.classList.add(cls);setTimeout(()=>who.classList.remove(cls),ms)}
function clearTelegraph(){clearTimeout(s.telegraphTimer);e.telegraph.classList.add('hidden');e.teleProgress.style.width='0%'}
function telegraph(move){clearTelegraph();const id=++s.telegraphId, duration=fighters[s.index].boss?1500:1900;const names={jab:'JAB',hook:'HOOK',upper:'UPPERCUT',feint:'FEINT'};const target=move==='upper'?'DODGE OR BLOCK':move==='hook'?'DODGE RIGHT / BLOCK':'BLOCK OR DODGE';e.teleMove.textContent=`INCOMING: ${names[move]||move.toUpperCase()}`;e.teleTarget.textContent=target;e.telegraph.classList.remove('hidden');e.telegraph.classList.add(`warn-${move}`);e.teleProgress.style.transition=`width ${duration}ms linear`;requestAnimationFrame(()=>e.teleProgress.style.width='100%');s.telegraphTimer=setTimeout(()=>{if(id===s.telegraphId)executeEnemy(move)},duration)}
function start(){if(s.clock)clearInterval(s.clock);s.active=true;s.over=false;s.index=0;s.round=1;s.php=100;s.star=0;s.combo=0;s.time=60;e.titleScreen.classList.add('hidden');enterRound();s.clock=setInterval(()=>{if(!s.active||s.over)return;if(--s.time<=0)(s.ehp<=s.php?win():lose());hud()},1000);music()}
function enterRound(){const f=fighters[s.index];s.emax=f.hp;s.ehp=f.hp;s.busy=s.enemyBusy=false;s.pattern=0;e.enemy.classList.toggle('enraged',!!f.boss);e.ename.textContent=f.name;e.ename.classList.toggle('boss-label',!!f.boss);banner(f.boss?'FINAL BOSS':`ROUND ${s.round}`,f.boss?'CHAMPIONSHIP FIGHT':f.name,true,f.boss?'championship':'');setTimeout(()=>banner('','',false),f.boss?2000:1200);hud();clearTelegraph();s.enemyTimer=setTimeout(enemyPlan,f.boss?1100:1300)}
function win(){if(!s.active)return;s.active=false;s.over=true;clearTelegraph();clearTimeout(s.enemyTimer);clearInterval(s.clock);anim(e.enemy,'ko',1100);tone('ko');e.status.textContent='KO!';if(s.index===fighters.length-1)banner('CHAMPION!','THE DOWNTOWN CIRCUIT IS YOURS',true,'championship');else{banner('KNOCKOUT!','NEXT ROUND INCOMING',true,'ko-banner');setTimeout(()=>{s.index++;s.round++;s.time=60;s.active=true;s.over=false;enterRound();s.clock=setInterval(()=>{if(s.active&&!s.over&&--s.time<=0)(s.ehp<=s.php?win():lose());hud()},1000)},1800)}}
function lose(){if(!s.active)return;s.active=false;s.over=true;clearTelegraph();clearTimeout(s.enemyTimer);clearInterval(s.clock);anim(e.player,'ko',1100);tone('ko');e.status.textContent='KO!';banner('KNOCKOUT','PRESS RESTART TO RISE',true,'ko-banner')}
function attack(type){if(!s.active||s.over||s.busy||s.enemyBusy)return;if(type==='upper'&&!(['a','d'].some(k=>s.pressed.has(k))))return;if(type==='star'&&s.star<100){hitText('CHARGE');return}s.busy=true;clearTelegraph();anim(e.player,type==='body'?'punch-body':type==='upper'?'punch-upper':'punch-star',type==='star'?550:380);const dmg=type==='body'?10:type==='upper'?18:38;s.ehp=Math.max(0,s.ehp-dmg);s.combo++;s.star=type==='star'?0:Math.min(100,s.star+(type==='upper'?16:12));hitText(type==='star'?'STAR!':type==='upper'?'UP!':'POW!');tone(type==='star'?'power':'hit');e.status.textContent=type==='star'?'STAR PUNCH':type==='upper'?'UPPERCUT':'BODY BLOW';hud();setTimeout(()=>{s.busy=false;s.ehp<=0?win():enemyPlan()},type==='star'?560:430)}
function dodge(dir){if(!s.active||s.over||s.busy)return;anim(e.player,dir<0?'dodge-left':'dodge-right',360);e.status.textContent=dir<0?'DODGE LEFT':'DODGE RIGHT'}function block(on){if(!s.active||s.over||s.busy)return;s.block=on;e.player.classList.toggle('blocking',on);e.status.textContent=on?'BLOCKING':'READY'}
function enemyPlan(){if(!s.active||s.over||s.enemyBusy)return;const f=fighters[s.index],move=f.pattern[s.pattern++%f.pattern.length];if(move==='pause'){e.status.textContent='WATCHING...';s.enemyTimer=setTimeout(enemyPlan,850);return}if(move==='block'){e.enemy.classList.add('blocking');e.status.textContent='ENEMY GUARD';setTimeout(()=>e.enemy.classList.remove('blocking'),700);s.enemyTimer=setTimeout(enemyPlan,900);return}if(move==='dodge'){anim(e.enemy,'dodge-left',380);e.status.textContent='ENEMY DODGE';s.enemyTimer=setTimeout(enemyPlan,1000);return}if(move==='feint'){e.status.textContent='FEINT!';hitText('FAKE');s.enemyTimer=setTimeout(()=>telegraph('hook'),750);return}telegraph(move)}
function executeEnemy(move){if(!s.active||s.over)return;clearTelegraph();s.enemyBusy=true;const f=fighters[s.index],blocked=s.block;anim(e.enemy,move==='upper'?'punch-upper':'punch-body',520);const dmg=f[move];s.php=Math.max(0,s.php-(blocked?Math.max(1,Math.round(dmg/3)):dmg));hitText(blocked?'GUARD!':move==='upper'?'UP!':'BAM!');tone(blocked?'hit':'power');e.status.textContent=blocked?'BLOCKED':`${move.toUpperCase()}!`;hud();if(s.php<=0){lose();return}s.enemyBusy=false;s.combo=0;hud();s.enemyTimer=setTimeout(enemyPlan,f.boss?1200:1600)}
function key(k,down){if(down){s.pressed.add(k);if(k==='a')dodge(-1);if(k==='d')dodge(1);if(k==='s')block(true);if(k===' ')attack('body');if(k==='w'&&(s.pressed.has('a')||s.pressed.has('d')))attack('upper');if(k==='p')attack('star')}else{s.pressed.delete(k);if(k==='s')block(false)}}
addEventListener('keydown',ev=>{const k=ev.key.toLowerCase();if(['a','d','s','w','p',' '].includes(k))ev.preventDefault();if(!s.pressed.has(k))key(k,true)});addEventListener('keyup',ev=>{const k=ev.key.toLowerCase();if(['a','d','s','w','p',' '].includes(k))key(k,false)});e.start.onclick=()=>{if(!s.audio){const C=AudioContext||webkitAudioContext;if(C)s.audio=new C}start()};e.restart.onclick=()=>{if(!s.audio){const C=AudioContext||webkitAudioContext;if(C)s.audio=new C}start()};e.music.onclick=()=>{s.musicOn=!s.musicOn;e.music.textContent=`♫ MUSIC: ${s.musicOn?'ON':'OFF'}`;if(s.musicOn)music()};hud();banner('READY','PRESS START',true);
